import Title from '@/components/ui/Title';

export default function TermsConditionsPage() {

  return (
    <main className='mt-28 lg:mt-40'>
      <section className='relative container my-10 lg:my-12 px-4 lg:px-8'>
        <div className='max-w-4xl mx-auto'>
          <Title titleMain='Terms & Conditions.' tagMain />
          <div className='opacity-70'>
            <p className='uppercase mt-8'>
              Syarat dan ketentuan di bawah ini harus dibaca sebelum menggunakan situs ini. penggunaan anda atas situs ini menunjukkan penerimaan anda terhadap syarat dan ketentuan ini.
            </p>
            <p className='mt-8'>Situs https://sightseaexpeditions.com/ (“Situs“) dikelola oleh Sightsea Expeditions, termasuk anak perusahaan dan perusahaan afiliasinya (“Kami“, “SightSea”). Dengan mengakses dan/atau menggunakan Situs, Anda sebagai seorang pengguna (“Anda” atau “Pengguna”) mengakui bahwa anda telah membaca dan memahami, dan menyetujui untuk terikat oleh Syarat dan Ketentuan yang ditetapkan di bawah ini (“Ketentuan”) dan syarat dan ketentuan lainnya dalam kaitannya dengan Situs, baik yang dituliskan secara tegas pada Ketentuan ini, maupun yang dibuat di luar Ketentuan ini namun memberikan rujukan pada Ketentuan ini. Apabila Anda tidak setuju untuk terikat dengan Ketentuan ini, Anda tidak dapat mengakses atau menggunakan bagian manapun dari Situs. Ketentuan ini merupakan perjanjian yang mengikat secara hukum bagi Anda. Anda harus setidaknya berusia delapan belas (18) tahun untuk menggunakan Situs ini.</p>
            <p className='mt-4'>Harap diketahui bahwa Kami dapat mengubah, memodifikasi, menambah dan menghapus Syarat ini sewaktu-waktu apabila diperlukan untuk mematuhi ketentuan peraturan perundang-undangan yang berlaku bagi Kami atau mencerminkan perubahan atas operasional Kami, dengan ketentuan bahwa Kami akan melakukan upaya yang wajar untuk menyampaikan pemberitahuan mengenai perubahan atas Ketentuan. Anda diwajibkan melakukan pengecekan Ketentuan secara berkala untuk memastikan kepatuhan Anda terhadap versi terkini. Dengan terus menggunakan Situs ini setelah adanya perubahan terhadap Ketentuan, Anda dianggap menyepakati dan menyetujui perubahan tersebut.</p>
            <p className='mt-4'>Jika Anda menggunakan salah satu layanan Kami yang lain, maka penggunaan Anda atas layanan tersebut tunduk pada syarat dan ketentuan yang berlaku untuk layanan tersebut, yang akan disediakan bagi Anda ketika Anda menggunakan layanan lainnya tersebut.</p>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>A. Lingkup Layanan Kami</h6>
              <p className='mt-4'>Melalui Situs, SightSea menyediakan platform daring sehingga Anda dapat menelusuri dan melakukan pemesanan berbagai jenis Layanan Liveaboard, Diving Trips, Dive Center dan Leisure Trips termasuk menggunakan metode pembayaran yang tersedia sehubungan dengan pilihan layanan tersebut (“Layanan”). Pengguna dapat melakukan pemesanan layanan yang disediakan oleh Pihak Ketiga sebagai Agen, dan/atau penyedia layanan lain yang bekerja sama dengan Sightsea (“Vendor”) di Situs. Dengan melakukan pemesanan melalui Situs, Anda akan dapat memesan Layanan Liveaboard, Diving Trips, Dive Center dan Leisure Trips (yang mana yang sesuai). Kami akan memberikan konfirmasi pemesanan melalui konfirmasi surat elektronik dan/atau metode lainnya yang tersedia. Kami berhak untuk menolak pemesanan yang tidak mematuhi Ketentuan ini dan peraturan perundang-undangan yang berlaku.</p>
              <p className='mt-4'>Meskipun Kami akan menggunakan keahlian Kami dengan hati-hati dalam menyediakan Layanan, Kami tidak memverifikasi, dan tidak menjamin, bahwa semua informasi yang diberikan oleh Vendor akurat, lengkap, benar atau terbaru, dan Kami tidak bertanggung jawab atas setiap kesalahan (termasuk kesalahan penempatan dan pengetikan), gangguan (baik sementara dan/atau parsial, kerusakan, perbaikan atau peningkatan ke situs atau sebaliknya), informasi yang tidak akurat, menyesatkan atau palsu atau informasi yang tidak disampaikan oleh Vendor kepada Kami. Hal ini mencakup setiap informasi yang ditampilkan pada Situs atau platform Kami lainnya yang diberikan oleh Vendor sehubungan dengan jenis layanan, harga-harga atau informasi lainnya yang diberikan oleh Vendor dari waktu ke waktu. Perubahan dalam kondisi pasar atau keadaan yang terjadi dapat menyebabkan perubahan dalam waktu singkat, yang menyebabkan informasi yang disediakan oleh Vendor tidak akurat atau tidak berlaku. Dalam hal terjadi masalah, Anda dapat menghubungi layanan pelanggan SightSea.</p>
              <p className='mt-4'>Dalam menyediakan Layanan, Kami menyediakan platform daring untuk menghubungkan Anda dengan Vendor. Sejauh diizinkan oleh hukum, Kami tidak bertanggung jawab atau berkewajiban atas tindakan atau kelalaian Vendor, dan Anda bertanggung jawab penuh atas kewajiban atau kewajiban apa pun kepada Vendor. Kami tidak membuat pernyataan apa pun dan tidak boleh ditafsirkan sebagai membuat rekomendasi atau saran tentang tingkat kualitas layanan atau peringkat Vendor yang terdaftar di Situs, dan dalam keadaan apa pun Kami tidak bertanggung jawab atau berkewajiban atas informasi, konten, produk, layanan atau materi lain apa pun yang diberikan atau disediakan oleh Vendor. Vendor dapat diperkenalkan dalam bentuk kelas yang berbeda berdasarkan faktor termasuk namun tidak terbatas pada ulasan, peringkat, atau faktor lainnya. Peringkat yang diberikan dihitung berdasarkan algoritme otomatis yang dapat diperbarui dan diubah sesuai kebijakan Kami.</p>
              <p className='mt-4'>Sejauh diizinkan oleh hukum, Kami memiliki hak untuk tidak menerima pengguna atau pemesanan manapun (atau dalam kasus-kasus tertentu membatalkan konfirmasi pemesanan) berdasarkan kebijakan tunggal Kami dan untuk alasan apa pun tanpa memberikan alasan penolakan/penampikan/pembatalan. Alasan untuk menolak pengguna atau pemesanan atau membatalkan konfirmasi pemesanan dapat termasuk namun tidak terbatas pada: pelanggaran Ketentuan ini, pengenaan sanksi perdagangan atau sanksi ekonomi oleh otoritas global atau nasional, embargo, larangan dalam peraturan, penipuan atau pencurian (atau indikasi atau dugaan penipuan atau pencurian), dugaan kegiatan kriminal, pemesanan yang mencurigakan, layanan yang tidak tersedia atau tidak lagi disediakan oleh Vendor, pengguna memberikan informasi yang tidak akurat, keliru atau menyesatkan, informasi atau transaksi, perilaku yang tidak pantas, ancaman, hinaan, penolakan untuk memberikan informasi, hambatan praktis, kesulitan atau kemacetan komunikasi, Kesalahan Nyata (selanjutnya dijelaskan di bawah ini), sejarah pelanggaran Ketentuan atau penolakan tersebut, atau dimasukkan pada setiap “daftar hitam” atau “daftar dalam pengawasan” oleh pemerintah atau organisasi internasional. Dengan memperhatikan ketentuan peraturan perundang-undangan yang berlaku, Kami dapat menghilangkan atau menghapus akun pengguna (termasuk Anda) Situs ini sewaktu-waktu, baik secara sementara atau permanen, termasuk namun tidak terbatas pada akun pengguna yang melakukan hal-hal yang disebutkan di atas (“Pengguna Yang Dihapus”). Pengguna yang Dihapus dilarang untuk mencoba menggunakan Situs dengan nama lain atau melalui pengguna lainnya.</p>
              <p className='mt-4'>Dalam kasus tertentu, Kami dapat membatalkan atau menolak pemesanan berkenaan dengan “Kesalahan Nyata”, yang tidak tergantung pada letak kesalahan berasal. Untuk menghindari keraguan, Kesalahan Nyata adalah kesalahan pada Situs (misalnya, namun tidak terbatas pada, dalam hal harga) yang tidak ada satu orang yang rasional pun akan menganggap layak atau membuat bisnis dimengerti. Jumlah yang dibebankan akan diganti tanpa biaya lebih lanjut dalam kasus seperti itu.</p>
              <p className='mt-4'>Setiap pembayaran atas pemesanan harus dilakukan secara langsung ke rekening bank milik SightSea atau metode pembayaran lain di SightSea. Kecuali jika SightSea diwajibkan untuk menahan pembayaran tersebut berdasarkan hubungan penguasaan dana pembayaran dengan Vendor terkait berdasarkan perjanjian terpisah yang berlaku untuk Vendor terkait, semua pembayaran tersebut akan menjadi milik SightSea dan jumlahnya akan jatuh tempo dan dibayarkan kepada Vendor terkait saat layanan yang terkait pembayaran disediakan atau pada waktu lain yang berlaku yang dipersyaratkan oleh Vendor terkait. SightSea tidak bertanggung jawab atas keabsahan reservasi, jika pembayaran tidak dilakukan langsung ke rekening bank SightSea atau saluran pembayaran SightSea.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>B. Pembatalan</h6>
              <p className='mt-4'>Dengan membuat pemesanan, pesanan atau reservasi melalui Situs, Anda menerima dan setuju dengan syarat dan ketentuan dari Vendor yang berlaku, termasuk yang berkaitan dengan kebijakan tentang pembatalan dan/atau ketidaktersediaan, atau sehubungan dengan permintaan khusus Anda yang mungkin diberikan kepada Vendor. SightSea tidak bertanggung jawab atas setiap pelanggaran syarat dan ketentuan yang disepakati antara Vendor dan Pengguna, atau yang didasarkan pada permintaan khusus Pengguna, sehingga pastikan Anda membaca syarat dan ketentuan Vendor dengan cermat sebelum Anda membuat pemesanan, order atau reservasi melalui Situs.</p>
              <p className='mt-4'>Apabila Pengguna melakukan pembatalan sebelum 60 hari dari tanggal yang telah dipesan, maka Pengguna akan mendapatkan pengembalian dana sebesar 50%. Namun jika Pengguna melakukan pembatalan setelah 60 hari dari tanggal yang telah dipesan maka Pengguna tidak akan mendapatkan pengembalian.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>C. Permintaan Khusus</h6>
              <p className='mt-4'>Dalam hal permintaan khusus sehubungan dengan pemesanan berdasar atas ketersediaan dan faktor lainnya, keberadaan permintaan khusus Anda dapat dikenakan harga dan/atau biaya tambahan oleh Vendor terkait berdasarkan kebijakan dan/atau ketentuan dari masing-masing Vendor. SightSea tidak bertanggung jawab atas ketersediaan dan/atau terpenuhinya permintaan khusus Anda oleh Vendor.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>D. Saran Perjalanan</h6>
              <p className='mt-4'>Dengan menampilkan destinasi tertentu, SightSea tidak menyatakan atau menjamin bahwa perjalanan ke tempat-tempat tersebut disarankan atau bebas risiko dan SightSea tidak akan bertanggung jawab atas kerusakan atau kerugian yang mungkin diakibatkan dari perjalanan ke destinasi tersebut. Dalam situasi apa pun, SightSea tidak akan bertanggung jawab atas insiden merugikan yang terjadi selama perjalanan atau selama Anda tinggal. Anda secara pribadi bertanggung jawab untuk pemilihan perjalanan, rute dan destinasi perjalanan, untuk sepanjang perjalanan Anda. SightSea tidak bertanggung jawab atas kerugian yang terjadi ketika Anda gagal membawa dokumen perjalanan yang diperlukan, seperti paspor Anda, e-tiket, e-voucher, dan hal-hal lainnya yang disebabkan oleh kesalahan dan/atau kelalaian Anda. SightSea juga tidak bertanggung jawab atas segala kesalahan dan/atau kelalaian yang disebabkan oleh Vendor.</p>
              <p className='mt-4'>Anda bertanggung jawab sepenuhnya untuk mendapatkan, menjaga dan menyediakan untuk ditunjukkan, izin-izin perjalanan atau persyaratan-persyaratan izin masuk orang asing yang sesuai dan sah (termasuk, namun tidak terbatas pada, visa atau izin-izin perjalanan lainnya, baik untuk transit atau keperluan lainnya) yang berlaku untuk Anda sebelum Anda memfinalisasi pengaturan perjalanan Anda sesuai dengan hukum yang berlaku di negara asal, tujuan, lewati atau transit dalam perjalanan Anda. SightSea tidak memiliki kewajiban dan tidak akan bertanggung jawab untuk memberitahu Anda mengenai pengaturan perjalanan dan izin-izin yang dibutuhkan oleh Anda agar dapat melaksanakan rencana perjalanan anda. SightSea tidak bertanggung jawab atau berkewajiban atas segala kerugian atau kerusakan yang timbul dari atau sehubungan dengan izin perjalanan Anda.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>E. Rating</h6>
              <p className='mt-4'>Rating / Peringkat yang ditampilkan di Situs hanya disediakan sebagai informasi bagi Pengguna saja, dan peringkat yang ada didasarkan pada informasi yang diberikan oleh pihak ketiga seperti Vendor, pengguna atau ulasan situs web lain. Kami tidak memverifikasi peringkat yang diberikan dan karena itu tidak bertanggung jawab atas keakuratan peringkat yang ada. Dengan ini Kami menyatakan penyangkalan klaim, kerugian atau kewajiban sehubungan dengan peringkat yang ditampilkan pada Situs.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>F. Harga Dan Promosi</h6>
              <p className='mt-4'>Kami dapat menawarkan harga yang lebih rendah dan/atau promosi dari waktu ke waktu. Harap diketahui bahwa hal tersebut mungkin memerlukan ketentuan dan persyaratan yang berbeda, misalnya, sehubungan dengan kebijakan pemesanan dan pengembalian dana. Apabila ada promosi yang diberikan oleh Vendor secara langsung, maka hak dan wewenang atas promosi tersebut sepenuhnya berada pada Vendor dan mungkin tidak berlaku untuk pemesanan yang dilakukan melalui SightSea.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>G. Biaya Tambahan & Pengembalian Dana</h6>
              <p className='mt-4'>Setiap harga yang tercantum pada Situs ini hanya tersedia dengan ketentuan tertentu dan harga tersebut dapat berubah tergantung pada berbagai faktor seperti namun tidak terbatas pada ketersediaan pemesanan, lamanya pemesanan dan/atau faktor lainnya. Harga yang tersedia dapat mencakup pajak tambahan dan biaya lainnya lagi tapi dalam keadaan tertentu mungkin tidak termasuk pajak dan biaya jasa lainnya (seperti biaya tips untuk pemandu wisata, biaya fasilitas lainnya (jika ada), dan biaya-biaya lainnya yang timbul dari penggunaan layanan selain layanan SightSea (apabila ada)). Anda setuju bahwa Anda bertanggung jawab untuk memverifikasi total biaya yang harus dibayar dan persyaratan lainnya dan rincian ketika email konfirmasi telah dikirim. Anda harus memverifikasi pemesanan dalam lembar pemesanan, dan Anda dapat membatalkan pemesanan setiap saat sebelum konfirmasi akhir dilakukan. Harga yang ditampilkan terperinci sehingga Anda dapat melihat jumlah yang harus dibayar, biaya tambahan apa pun yang disebabkan biaya antarbank yang dikenakan untuk biaya pengiriman akan dibebankan kepada Anda. Jika terdapat kekurangan dalam jumlah yang dibayarkan, maka SightSea dapat memberikan notifikasi surat elektronik mengenai kekurangan dalam jumlah yang harus dibayarkan Anda.</p>
              <p className='mt-4'>Dalam hal Anda membatalkan pemesanan, maka anda akan mendapatkan pengembalian dana sebesar 50% apabila Anda melakukan pembatalan sebelum 60 hari dari tanggal yang telah dipesan. Namun apabila Anda melakukan pembatalan setelah 60 hari dari tanggal yang telah dipesan maka Anda tidak akan mendapatkan pengembalian.</p>
              <p className='mt-4'>Jika Anda memiliki pertanyaan tentang Layanan, Anda dapat menghubungi layanan pelanggan SightSea (selama waktu operasional layanan pelanggan yang ditentukan oleh SightSea). Untuk setiap pembatalan lainnya, sesuai kebijakan SightSea dan Vendor, Sightsea pertama-tama akan melakukan verifikasi pesanan sebelum menentukan besaran pengembalian kepada Anda. Apabila Sightsea telah melakukan verifikasi maka ketentuan pembatalan akan berlaku yaitu apabila Anda melakukan pembatalan sebelum 60 hari dari tanggal yang telah dipesan, maka Anda akan mendapatkan pengembalian dana sebesar 50%. Namun jika Anda melakukan pembatalan setelah 60 hari dari tanggal yang telah dipesan maka Anda tidak akan mendapatkan pengembalian.</p>
              <p className='mt-4'>SightSea akan melakukan pengembalian dana kepada Anda (apabila ada) dengan cara menggunakan bank transfer ke rekening pembayar sesuai dengan pembayaran transfer yang dilakukan oleh Anda dan/atau ke rekening bank yang dicantumkan dalam formulir pengembalian dana yang diberikan kepada kami.</p>
              <p className='mt-4'>Pengembalian dana untuk transaksi pembayaran menggunakan Transaksi Bank kepada Pengguna dan Anda dapat menghubungi layanan pelanggan SightSea untuk detail lebih lanjut mengenai perkiraan durasi penerimaan pengembalian dana Anda.</p>
              <p className='mt-4'>SightSea tidak akan bertanggung jawab atas setiap penerbitan e-tiket, e-voucher, atau transaksi lainnya yang digugurkan akibat jumlah yang ditransfer tidak akurat oleh pengguna atau pembayaran yang tidak dilakukan melalui metode pembayaran resmi yang tersedia di Situs. Setiap transfer yang dilakukan melebihi batas waktu untuk transfer akan mengakibatkan pemesanan digugurkan. Untuk waktu nyata (real-time) transfer antar bank, Anda harus menggunakan ATM. Setelah menyelesaikan transfer antar bank, harap konfirmasi pembayaran Anda dengan mengisi formulir konfirmasi pembayaran.</p>
              <p className='mt-4'>Tunduk pada ketentuan fasilitas pemrosesan pembayaran, kami pada dasarnya akan memproses pengembalian dana anda, baik sukarela maupun tidak, dengan melakukan pengembalian dana melalui metode pembayaran awal yang anda gunakan untuk membayar Pemesanan Terkonfirmasi. Jika pengembalian dana anda tidak dapat dibatalkan melalui metode pembayaran awal yang anda gunakan, atau anda menggunakan transfer bank atau melakukan pembayaran melalui mitra pembayaran offline kami sebagai metode pembayaran awal untuk membayar Pemesanan Terkonfirmasi, kami akan mentransfer pengembalian dana tersebut hanya ke rekening bank tertentu yang berlaku yang telah anda daftarkan di Situs ketika mengajukan permintaan pengembalian dana (“Rekening Bank Tertentu”). Kami berhak menahan dan menolak transfer pengembalian dana apa pun ke Rekening Bank Tertentu yang tidak ada kesesuaian dengan informasi pribadi anda atau jika kami menganggap atau mencurigai secara wajar bahwa permintaan pengembalian dana mungkin melanggar undang-undang tentang pencucian uang, pendanaan terorisme, penipuan, atau aktivitas kriminal lainnya, atau berpotensi mengandung unsur perilaku yang melawan hukum. Kami dapat melaporkan dugaan pelanggaran hukum kepada pihak penegak hukum yang bersangkutan (jika berlaku) untuk mematuhi kewajiban hukum kami sebagaimana yang diberlakukan oleh hukum yang berlaku.</p>
              <p className='mt-4'>Kami tidak bertanggung jawab atas kebenaran, keakuratan atau kelengkapan informasi yang Anda berikan. Sejauh diizinkan oleh hukum yang berlaku, jika (a) kami tidak dapat mengembalikan pembayaran ke metode pembayaran awal anda, baik karena disebabkan oleh penyedia layanan pemrosesan pembayaran, SightSea atau anda sendiri; (b) anda gagal memberikannya kepada kami rincian yang diperlukan untuk memungkinkan kami memproses pengembalian dana anda, gagal mendaftar atau menambahkan Rekening Bank Tertentu di Situs, Rekening Bank Yang Ditunjuk yang anda tambahkan tidak akurat, tidak valid, atau tidak dapat ditemukan oleh sistem bank; dan (c) anda tidak dapat dihubungi, atau anda tidak menanggapi kami setelah kami melakukan upaya untuk menghubungi anda, baik melalui alamat email atau nomor telepon anda yang terdaftar, anda akan dianggap tidak dapat dihubungi untuk tujuan pemrosesan pengembalian dana anda, dan SightSea berhak berhenti memproses permintaan pengembalian dana anda.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>H. Akun Pengguna</h6>
              <p className='mt-4'>Anda harus membuat akun untuk menggunakan Layanan. Untuk tujuan pendaftaran, Kami akan mengumpulkan dan memproses informasi pribadi anda, seperti nama, alamat surat elektronik (surel), dan nomor telepon genggam Anda ketika Anda melakukan pendaftaran. Anda harus memberikan Kami informasi yang akurat, lengkap dan terkini dan setuju untuk bukti identitas diri yang mungkin Kami minta dengan alasan yang jelas. Kami akan mengumpulkan, menggunakan, mengungkapkan, dan memproses informasi pribadi Anda sesuai dengan Kebijakan Privasi Kami yang tersedia di Persyaratan Privasi Penggunaan Data Pribadi.</p>
              <p className='mt-4'>Hanya Anda yang berhak untuk menggunakan akun Anda sendiri dan Anda menyatakan dan menjamin bahwa Anda tidak akan mengizinkan pihak lain untuk menggunakan identitas atau akun Anda untuk alasan apapun, kecuali diizinkan oleh SightSea. Anda tidak dapat mengalihkan atau memindahkan akun Anda kepada pihak lain manapun. Anda harus menjaga keamanan dan kerahasiaan kata sandi akun Anda dan identifikasi yang Kami sediakan untuk anda. Dalam hal terdapat pengungkapan atas kata sandi anda, dalam hal apapun juga yang menyebabkan adanya pengguna yang tidak sah atas akun atau identitas Anda, pesanan yang diterima atas penggunaan yang tidak sah tersebut akan tetap dianggap sebagai pesanan yang sah dan Kami akan memproses pesanan tersebut. Anda dengan ini menyatakan bahwa SightSea tidak bertanggung jawab atas setiap kerugian atau kerusakan yang timbul atas penyalahgunaan akun anda tersebut.</p>
              <p className='mt-4'>Jika anda tidak lagi mempunyai kontrol atas akun Anda, Anda wajib untuk secepatnya memberitahukan kepada Kami (contoh, tanpa pembatasan: akun Anda diretas dengan cara apapun atau telepon Anda dicuri) sehingga Kami dapat memblokir sementara dan/atau menonaktifkan akun Anda sebagaimana diperlukan. Harap dicatat bahwa Anda bertanggung jawab atas penggunaan akun Anda dan mungkin bertanggung jawab atas akun Anda meskipun dalam hal akun Anda disalahgunakan oleh pihak lain.</p>
              <p className='mt-4'>SightSea memiliki hak penuh untuk memblokir, menghapus, atau menonaktifkan akun Anda untuk sementara waktu atas kebijakan Kami sendiri dan untuk alasan apa pun tanpa memberikan alasan pemblokiran, penghapusan, atau penonaktifan akun Anda dengan ketentuan bahwa hal ini tidak akan memengaruhi kewajiban Kami untuk menyediakan Layanan apa pun yang telah telah dibeli oleh Anda sebelum waktu itu (kecuali Kami juga membatalkan Layanan tersebut sebagaimana diizinkan oleh Ketentuan ini). Alasan pemblokiran, penghapusan, atau penonaktifan akun Anda mungkin termasuk tetapi tidak terbatas pada:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>pelanggaran Syarat ini,</li>
                <li>larangan di peraturan,</li>
                <li>penipuan atau pencurian (atau indikasi atau sangkaan penipuan atau penipuan)</li>
                <li>kecurigaan adanya tindak kriminal,</li>
                <li>pesanan yang mencurigakan,</li>
                <li>pengguna memberikan informasi yang tidak akurat, salah atau menyesatkan,</li>
                <li>melakukan perbuatan yang tidak pantas, ancaman, atau hinaan,
                  menolak memberikan informasi,</li>
                <li>adanya hambatan praktis,</li>
                <li>kesulitan atau kendala komunikasi, atau</li>
                <li>pengguna termasuk ke dalam “daftar hitam” atau “daftar pengamatan” oleh pemerintah atau organisasi internasional.</li>
              </ol>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>I. Detail Dan Prosedur Pembayaran</h6>
              <p className='mt-4'>Pembayaran dilakukan dalam jumlah dan mata uang sebagaimana dinyatakan, belum termasuk biaya bank atau biaya lain apa pun yang dibebankan oleh SightSea. Segala bentuk perpajakan dan retribusi, sesuai dengan ketentuan perundang-undangan yang berlaku di bidang perpajakan, akan ditanggung oleh Pengguna. Untuk semua bentuk reservasi, Anda harus melakukan pembayaran sebelum batas waktu yang telah ditentukan. Jika pembayaran tidak dilakukan, maka SightSea berhak untuk membatalkan semua reservasi atau mengabaikan proses pemesanan.</p>
              <p className='mt-4'>Metode pembayaran termasuk namun tidak terbatas pada transfer bank. Untuk pembayaran melalui transfer bank, Anda harus memberikan tanda terima transfer bank sebagai bukti pembayaran reservasi yang tercantum dalam surat elektronik konfirmasi SightSea. Anda harus mengikuti prosedur yang terdapat dalam surat elektronik konfirmasi.</p>
              <p className='mt-4'>Setelah Anda melakukan pembayaran penuh, SightSea akan menempatkan pesanan dan mengeluarkan kode reservasi, yang akan disertai dengan:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>Nomor Invoice;</li>
                <li>Nama Pelanggan;</li>
                <li>Rincian Pemesanan; dan</li>
                <li>Nomor Telepon/Ext..</li>
              </ol>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>J. Hak Dan Kewajiban</h6>
              <p className='mt-4'>SightSea dengan ini memberikan Pengguna hak terbatas tertentu (merupakan “Lisensi Terbatas”), yang tidak dapat dipindahkan atau didelegasikan, untuk mengakses dan menggunakan Situs sejauh mana dinyatakan diizinkan oleh Ketentuan ini. Sehubungan dengan Lisensi Terbatas ini, Kami tidak memberikan Anda hak atau lisensi lainnya sehubungan dengan penggunaan Situs; hak atau lisensi yang tidak diberikan secara tersurat, sepenuhnya dimiliki oleh SightSea atau pemilik pihak ketiga lainnya dari lisensi tersebut. Konten yang tersedia di Situs, termasuk setiap informasi, data, teks, gambar, suara, grafik, video, pesan, ulasan, atau materi lainnya, termasuk infrastruktur perangkat lunak yang digunakan untuk menyediakan konten (“Konten”) sepenuhnya dimiliki oleh SightSea atau pemasok dan penyedia layanannya, termasuk namun tidak terbatas pada Vendornya (sebagaimana berlaku). Anda dapat menggunakan Situs untuk melakukan reservasi dan Anda dengan ini menjamin bahwa Anda tidak akan mengajukan permintaan reservasi palsu. Anda dengan ini menyatakan untuk memastikan bahwa informasi pembayaran yang Anda berikan adalah benar dan sepenuhnya akurat. Anda juga menjamin untuk memberikan alamat surat elektronik yang tepat dan akurat, alamat surat menyurat dan/atau rincian informasi kontak Anda.</p>
              <p className='mt-4'>Berkaitan dengan Ketentuan dari Situs, Anda setuju untuk tidak menggunakan Situs atau Konten untuk tujuan komersial atau baik secara langsung maupun tidak langsung untuk tujuan selain penggunaan pribadi atau untuk tujuan yang melanggar hukum (dilarang oleh hukum) atau melakukan tindakan yang melanggar Ketentuan ini. Kecuali dengan kesepakatan tertulis dari SightSea, Anda setuju untuk tidak memodifikasi, menyalin, mendistribusikan, mengirimkan, menampilkan, mereproduksi, mempublikasikan, melisensikan, menciptakan karya turunan dari, mentransfer, atau menjual atau menjual kembali setiap informasi, perangkat lunak, produk atau layanan yang diperoleh sehubungan dengan Situs. Selain itu, Anda setuju untuk tidak:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>menggunakan Situs ini atau Konten untuk tujuan komersial tanpa izin dari SightSea;</li>
                <li>mengakses, memonitor atau menyalin Konten pada Situs menggunakan teknologi, perangkat lunak, atau program apa pun baik secara manual atau otomatis untuk tujuan apa pun tanpa izin tertulis dari SightSea;</li>
                <li>melakukan tindakan apa pun yang membebani atau mungkin membebani, tanggungan yang tidak wajar pada Situs atau infrastruktur Situs;</li>
                <li>membuat tautan utama ke Situs ini (termasuk namun tidak terbatas pada jalur pemesanan) untuk tujuan apa pun tanpa persetujuan tertulis dari SightSea;</li>
                <li>menjual kembali, menggunakan, menyalin, melakukan pengawasan (seperti menggunakan atau memasang program spider atau scrape), menampilkan, mengunduh atau melakukan produksi Konten apa pun, perangkat lunak, produk, layanan yang tersedia melalui Situs untuk tujuan komersial atau tujuan/kegiatan kompetisi;</li>
                <li>mereproduksi Situs (melalui “frame” atau “mirror”) atau mengatur bagian dari Situs ini pada setiap situs web lain tanpa persetujuan tertulis sebelumnya;</li>
                <li>mengirim pengumuman ke atau melalui Situs yang melanggar hukum, peraturan, atau aturan, atau yang dapat mendukung kegiatan yang melanggar hukum atau kegiatan kriminal;</li>
                <li>mengirimkan atau menyediakan tautan ke atau mengirimkan pengumuman yang mengandung materi yang dapat dianggap berbahaya, cabul, pornografi, tidak senonoh, kekerasan, rasis, atau merupakan diskriminasi, hinaan, ancaman, pelecehan, penindasan, kebencian atau materi tidak menyenangkan lainnya, sesuai dengan kebijaksanaan SightSea ini;</li>
                <li>mengirimkan atau menyediakan tautan ke setiap pengumuman yang mengandung bahasa pencemaran nama baik, fitnah, dan kebohongan;</li>
                <li>mengirim spam atau pesan lain yang tidak diminta atau menyebabkan gangguan, atau ketidaknyamanan;</li>
                <li>mengirimkan atau menyimpan materi yang mungkin melanggar kekayaan intelektual atau hak-hak lain dari entitas atau orang tertentu, termasuk namun tidak terbatas pada hak cipta, paten, merek dagang, rahasia dagang atau informasi rahasia atau publikasi;</li>
                <li>mengirimkan atau menyimpan materi yang dilarang oleh hukum yang berlaku atau melanggar hak dan kewajiban yang ada berdasarkan hubungan kontraktual;</li>
                <li>mengirim atau menyimpan materi apa pun yang mengandung virus perangkat lunak, worm, trojan horse, atau kode komputer berbahaya lainnya;</li>
                <li>meniru orang atau kelompok apa pun, atau menyatakan dengan keliru atau salah mengemukakan kepada seseorang atau entitas terhadap hubungan atau mengambil identitas palsu jika tujuannya untuk menyesatkan atau memperdaya;</li>
                <li>memanipulasi atau memalsukan informasi yang bertujuan untuk menyamarkan asal-usul pernyataan yang Anda berikan;</li>
                <li>menggunakan Situs dengan cara apa pun yang dapat merusak, menonaktifkan, menghambat, atau mengganggu penggunaan Situs atau pengguna lain dari peralatan komputer, atau menyebabkan kerusakan, gangguan atau membatasi fungsi dari perangkat lunak, perangkat keras atau peralatan telekomunikasi;</li>
                <li>mendapatkan akses tidak sah atau melakukan modifikasi yang tidak sah ke Situs atau situs web terkait lainnya, akun lainnya, sistem komputer, jaringan yang terhubung dengan Situs dengan cara meretas, pencurian kata sandi atau hal-hal lain yang sejenis;</li>
                <li>memperoleh atau berusaha memperoleh materi atau informasi apa pun dengan cara yang tidak ditujukan untuk disediakan oleh Situs (termasuk namun tidak terbatas pada destinasi lain yang disediakan oleh Situs). Hal ini termasuk namun tidak terbatas pada, memperoleh atau mengumpulkan informasi tentang orang lain seperti alamat email;</li>
                <li>terlibat dalam tindakan penipuan atau tindakan yang bertujuan untuk memanipulasi halaman hasil mesin pencari (SERP) atau melakukan optimasi mesin pencari (“SEO”). Praktik SEO dianggap tidak etis atau merupakan “spamdexing” termasuk namun tidak terbatas pada cloaking, metadata, tag judul, scraping konten, skema tautan, google bomb, pencarian kata kunci, teks tersembunyi atau tautan tersembunyi, skema tautan, komentar yang mengandung spam dan hal-hal lain;</li>
                <li>tindakan lain apa pun yang dapat memberi pengaruh negatif atau mengakibatkan kerusakan pada Situs, SightSea atau afiliasinya dan karyawan, atau reputasi SightSea;</li>
                <li>memodifikasi atau membuat karya turunan berdasarkan Situs dan/atau Layanan, atau merekayasa balik atau mengakses perangkat lunak yang mendasarinya untuk alasan apa pun; atau</li>
                <li>menggunakan Situs untuk membangun produk atau layanan yang kompetitif.</li>
              </ol>
              <p className='mt-4'>Kecuali ditentukan lain secara tegas, situs web manapun tidak diizinkan untuk membuat tautan ke halaman lain selain halaman utama Situs atau frame atau halaman web atau materi yang terkandung di dalamnya, atau membuat tautan ke aspek Situs dalam bentuk surat elektronik dengan tujuan komersial tanpa persetujuan tertulis yang dinyatakan oleh SightSea.</p>
              <p className='mt-4'>Dengan menempatkan pesanan melalui Situs ini, Anda dengan ini menyatakan dan menjamin bahwa Anda tidak diduga dan/atau terlibat dan/atau dikenakan larangan atau pembatasan apa pun oleh program sanksi apa pun, atau dikenakan hukuman di bawah rezim anti pencucian uang dan pendanaan terorisme mana pun.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>K. Hak Atas Konten Pengguna</h6>
              <p className='mt-4'>engan menyelesaikan pemesanan, Anda dengan ini setuju untuk menerima surat elektronik yang berisi undangan untuk memberikan ulasan atau ulasan konten sehubungan dengan pemilihan Vendor. SightSea memiliki kebijakan tunggal apakah ulasan Anda akan muncul di Situs. SightSea dapat menampilkan ulasan, yang mungkin berisi komentar, tingkat layanan, dan nama Anda. Pengguna memiliki hak untuk memberikan ulasan yang mungkin memuat media (foto dan/atau video) sehubungan dengan pemilihan Vendor. Dengan melakukan hal tersebut, Anda dengan ini setuju untuk tunduk syarat dan ketentuan yang tertuang pada bagian ini.</p>
              <p className='mt-4'>Dalam memberikan ulasan yang mungkin memuat media (foto dan/atau video) maupun tidak, Anda setuju untuk memastikan bahwa:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>Anda memiliki dan mengendalikan semua hak atas ulasan yang Anda berikan ke Situs;</li>
                <li>Anda memberi Kami lisensi abadi, tidak dapat dibatalkan, bebas royalti, mendunia, dapat disublisensikan, dan dapat dialihkan untuk menggunakan ulasan Anda, termasuk semua hak kekayaan intelektual di dalamnya, sehubungan dengan operasi bisnis Kami termasuk pengoperasian dan pengelolaan Situs;</li>
                <li>konten ulasan akurat dan tidak mengandung penggambaran yang keliru;</li>
                <li>penggunaan atau kinerja atau pengiriman konten ulasan tidak melanggar Syarat atau undang-undang dan peraturan yang berlaku, Anda tidak melanggar hak pihak ketiga, dan Anda tidak menyebabkan cedera pada pihak mana pun; dan</li>
                <li>Anda harus memikul semua tanggung jawab atas konten dari ulasan yang Anda berikan atau kirimkan.</li>
              </ol>
              <p className='mt-4'>Ulasan konten yang diberikan akan dianggap tidak terdiri atas informasi rahasia dan SightSea tidak akan memiliki kewajiban untuk memperlakukan ulasan konten sebagai informasi rahasia.</p>
              <p className='mt-4'>Tanpa membatasi ketentuan yang terdapat dalam Syarat ini, SightSea memiliki kebijakan tunggal untuk menggunakan ulasan konten yang dianggap sesuai, termasuk namun tidak terbatas pada penghapusan, pemotongan, modifikasi, atau mengoreksi ulasan. SightSea tidak memiliki kewajiban untuk membayar konten yang Anda kirimkan dalam ulasan, termasuk namun tidak terbatas pada ulasan konten yang telah diubah, dihilangkan atau dipotong. SightSea tidak akan memiliki kewajiban untuk menyediakan atau mencantumkan atau menyebutkan penulis atau pihak ketiga lainnya. Dalam hal apa pun, Anda dengan ini setuju bahwa sehubungan dengan konten dari ulasan:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>Anda tidak memerlukan atribusi atau identifikasi dalam setiap karya turunan;</li>
                <li>Anda memberikan persetujuan bahwa seluruh ulasan yang Anda serahkan kepada SightSea dan karyawannya, suksesornya, dan penerima pengalihan dengan cara apapun, kapan pun. Hal ini termasuk namun tidak terbatas untuk mempublikasikan dan mereproduksi ulasan tersebut;</li>
                <li>Anda dengan ini melepaskan hak dan setuju untuk tidak mengklaim hak apa pun dalam ulasan konten; dan</li>
                <li>Anda dengan ini mengganti kerugian dan membebaskan SightSea dan karyawannya, afiliasi, pemegang hak, penggantian, dan menunjuk dari setiap klaim sehubungan dengan konten dari ulasan.</li>
              </ol>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>L. Pembatasan Penggunaan</h6>
              <p className='mt-4'>Anda dengan ini setuju untuk tidak menggunakan Situs atau Konten untuk kegiatan yang tidak sah atau melanggar hukum. Anda setuju bahwa Anda tidak akan menggunakan peralatan apa pun, perangkat lunak, atau teknologi lainnya yang mungkin menghambat atau berusaha menghalangi pengoperasian Situs ini. Anda setuju untuk tidak menggunakan Situs ini atau Kontennya untuk tujuan komersial. Anda setuju untuk tidak berupaya, membuat, mencari, menggunakan atau mengirim sarana otomatis atau bentuk lain dari teknologi untuk mengumpulkan atau mendapatkan informasi dari Situs ini, atau cara lain untuk berinteraksi dengan Situs ini.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>M. Hak Kekayaan Intelektual</h6>
              <p className='mt-4'>Semua hak kekayaan intelektual (“Hak Kekayaan Intelektual”) termasuk namun tidak terbatas pada hak cipta, paten, nama domain, merek dagang, merek layanan, logo, simbol atau desain lainnya dll, dalam Konten pada Situs yang dimiliki oleh SightSea dan afiliasinya atau oleh Vendor atau pihak ketiga lain yang SightSea memiliki pengaturan komersial dengannya. Semua informasi dan materi, termasuk namun tidak terbatas pada: perangkat lunak, teks, data, grafik, gambar, suara, video, merek dagang, logo, ikon, kode html dan kode-kode lainnya di Situs dilarang untuk dipublikasikan, dimodifikasi, disalin, direproduksi, digandakan atau diubah dengan cara apa pun di luar area Situs tanpa izin tertulis dari SightSea. Jika Anda melanggar hak-hak tersebut, SightSea berhak mengajukan tuntutan-tuntutan perdata atas seluruh kerugian atau kerusakan yang diderita. Pelanggaran-pelanggaran ini juga dapat merupakan tindak pidana.</p>
              <p className='mt-4'>SightSea dan/atau afiliasinya adalah pemilik Hak Kekayaan Intelektual tertentu. Kecuali dinyatakan secara tegas dalam Ketentuan ini, tidak ada ketentuan dalam Ketentuan ini yang dapat ditafsirkan sebagai memberi Anda lisensi atau hak apa pun, tersirat atau tidak, untuk menggunakan, memiliki, mendistribusikan, atau memodifikasi Hak Kekayaan Intelektual SightSea. Nama produk dan perusahaan lain yang terdapat di Situs, termasuk nama, merek dagang, merek, merek layanan, logo, simbol, atau desain lainnya mungkin dimiliki atau dilisensikan untuk digunakan oleh pihak ketiga. Penggunaan Hak Kekayaan Intelektual pihak ketiga di Situs tidak dianggap sebagai rekomendasi atau sponsor untuk Situs oleh pihak ketiga. SightSea memiliki hak cipta atas Situs, dan Anda tidak boleh menggunakan, memiliki, mendistribusikan, atau mengubah Hak Kekayaan Intelektual yang dimiliki oleh SightSea dan afiliasinya tanpa persetujuan tertulis dari SightSea.</p>
              <p className='mt-4'>Situs ini berisi Kekayaan Intelektual SightSea, termasuk namun tidak terbatas pada teks, perangkat lunak, foto, grafik, video, musik dan suara. Seluruh Konten dalam Situs ini dilindungi oleh undang-undang hak cipta dan peraturan terkait hak kekayaan intelektual lainnya yang relevan. Kami dan pemberi lisensi kami memiliki hak cipta dan/atau hak-hak lainnya atas pemilihan, koordinasi, pengaturan, dan perbaikan Konten dan konten asli. Anda tidak boleh memodifikasi, mereproduksi, menyalin, melakukan, menampilkan, mempublikasikan, atau mengeksploitasi Konten, secara keseluruhan atau sebagian, kecuali dinyatakan lain secara tegas dalam Syarat ini.</p>
              <p className='mt-4'>Seluruh Konten dilindungi oleh undang-undang hak cipta dan peraturan terkait hak kekayaan intelektual lainnya yang relevan. Kami dan pemberi lisensi Kami memiliki hak cipta dan/atau hak lain atas pemilihan, koordinasi, pengaturan, dan perbaikan Konten dan konten asli. Anda tidak boleh memodifikasi, mereproduksi, menyalin, menampilkan, mempublikasikan, atau mengeksploitasi Konten, secara keseluruhan atau sebagian, kecuali jika Anda memiliki persetujuan tertulis dari SightSea.</p>
              <p className='mt-4'>Kecuali ditentukan lain, perangkat lunak yang diperlukan untuk penyediaan layanan, perangkat lunak yang tersedia untuk digunakan pada Situs ini, dan Hak Kekayaan Intelektual dalam Konten di Situs dimiliki oleh SightSea, afiliasinya atau perusahaan yang terkait, pemberi lisensi, pemasok dan penyedia konten. SightSea tidak akan bertanggung jawab atas kekayaan intelektual yang dimiliki oleh pihak ketiga atau atas pelanggaran hak kekayaan intelektual yang dimiliki oleh pihak ketiga.</p>
              <p className='mt-4'>Anda dapat menggunakan informasi di Situs hanya untuk penggunaan pribadi, non-komersial. Kecuali ditentukan lain, dan secara tegas diizinkan oleh hukum hak cipta, Anda tidak dapat menyalin, mereproduksi, mendistribusikan, mengirimkan ulang, mempublikasikan atau sebaliknya mengeksploitasi secara komersial setiap unduhan yang Anda buat dari Situs tanpa izin dari pemilik Hak Kekayaan Intelektual. Bahkan jika Anda mendapatkan izin yang diperlukan, Anda dilarang untuk melakukan perubahan atau penghapusan. Anda dengan ini menerima dan setuju bahwa mengunduh Konten apa pun tidak memberikan Anda Hak Kekayaan Intelektual atas Konten tersebut.</p>
              <p className='mt-4'>SightSea dalam membuat Situs, menyiapkan kode sumber dan melakukan dukungan perangkat lunak, dapat melisensikan penggunaan perangkat lunak sumber terbuka dari pihak ketiga melalui GNU General Public Licence (GPL), Setiap penggunaan SightSea terhadap perangkat lunak sumber terbuka SightSea dan hak kekayaan intelektual pihak ketiga adalah dengan lisensi atau izin yang diperlukan.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>N. Klaim Pelanggaran Hak Kekayaan Intelektual</h6>
              <p className='mt-4'>Jika terdapat bukti pelanggaran Hak Kekayaan Intelektual Anda, maka Anda atau perwakilan Anda (secara bersamaan, “Pengirim”) dapat mengirimkan pemberitahuan yang berisi rincian sebagai berikut yang terdata di bawah ini:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>Nama dan alamat Pengirim;</li>
                <li>Dalam hal Pengirim bukan pemilik Hak Kekayaan Intelektual atau lisensi eksklusif, maka harus mencantumkan nama dan alamat pemilik Hak Kekayaan Intelektual;</li>
                <li>Dalam hal alamat Pengirim tidak di Indonesia, Pengirim harus memberikan alamat sementara di Indonesia;</li>
                <li>Nomor telepon, faksimili (jika ada) dan alamat surat elektronik Pengirim;</li>
                <li>Detail yang cukup sehingga dapat membuktikan adanya pelanggaran hak kekayaan intelektual, termasuk alamat online dari salinan elektronik;</li>
                <li>Permintaan Pengirim untuk menghapus atau menonaktifkan akses ke salinan elektronik atau versi yang dilanggar;</li>
                <li>Pernyataan bahwa Pengirim dengan itikad baik mengenali adanya pelanggaran sebagaimana diidentifikasi dalam Pasal ini;</li>
                <li>Pernyataan bahwa informasi yang diberikan dalam pemberitahuan akurat;</li>
                <li>Pernyataan bahwa Pengirim (i) adalah pemilik atau pemegang eksklusif hak kekayaan intelektual yang dilanggar; atau (ii) memiliki kewenangan hukum untuk bertindak atas pemilik atau pemegang eksklusif; dan</li>
                <li>Pernyataan bahwa Pengirim tunduk pada hukum Republik Indonesia dan bahwa semua klaim, perselisihan, kontroversi atau perbedaan yang timbul dari pelanggaran hak kekayaan intelektual harus terlebih dahulu secara musyawarah dengan itikad baik untuk mencapai mufakat dalam waktu enam puluh (60) hari sejak tanggal pemberitahuan tentang adanya perselisihan. Namun, jika perselisihan tersebut tidak dapat diselesaikan melalui musyawarah dalam waktu enam puluh (60) hari, maka perselisihan tersebut wajib dirujuk ke dan diputuskan melalui Badan Arbitrase Nasional Indonesia (BANI). Kedudukan arbitrase tersebut harus dilakukan di Indonesia.</li>
              </ol>
              <p className='mt-4'>Surat tersebut harus ditandatangani oleh pengirim dan disampaikan secara fisik dan melalui email ke alamat berikut:</p>
              <p className='mt-4 italic text-center'>Alamat: Gg Melati No.18 Plawa Seminyak, Badung Regency Bali</p>
              <p className='mt-4'>Kami akan meninjau dan menangani pemberitahuan sesuai dengan persyaratan di atas serta sesuai dengan hukum Republik Indonesia dan Anda setuju untuk mengganti kerugian dan tidak menyalahkan Kami atas setiap kerugian atau kerusakan yang mungkin terjadi sebagai akibat dari penipuan, pemalsuan atau tuduhan palsu dari pelanggaran hak kekayaan intelektual.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>O. Pembatasan Tanggung Jawab</h6>
              <p className='mt-4'>ANDA DENGAN INI MENYATAKAN UNTUK DAN SETUJU BAHWA SEJAUH MANA DIIZINKAN OLEH HUKUM YANG BERLAKU:</p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>LAYANAN DAN KONTEN SITUS INI DIBERIKAN BERDASARKAN “SEBAGAIMANA ADANYA” DAN “SEBAGAIMANA TERSEDIA”. KAMI DENGAN INI MENYATAKAN SECARA TEGAS BAHWA KAMI TIDAK MEMBUAT GARANSI ATAU JAMINAN APA PUN, BAIK TERSURAT MAUPUN TERSIRAT, SEHUBUNGAN DENGAN KELAYAKAN USAHA DARI PRODUK ATAU LAYANAN, ATAU KESESUAIAN PRODUK DAN LAYANAN YANG KAMI SEDIAKAN UNTUK TUJUAN TERTENTU DAN MENENTANG PENYALAHGUNAAN HAK-HAK MANA YANG BERLAKU;</li>
                <li>KAMI TIDAK MENJAMIN BAHWA: (i) FUNGSI, LAYANAN DAN FITUR KEAMANAN YANG DISEDIAKAN DALAM SITUS INI TIDAK AKAN TERGANGGU ATAU BEBAS DARI KESALAHAN; (Ii) KESALAHAN ATAU KEGAGALAN AKAN DIPERBAIKI; ATAU (iii) SITUS ATAU SERVER MEMBERIKAN LAYANAN YANG BEBAS DARI VIRUS, MALWARE ATAU KOMPONEN BERBAHAYA;</li>
                <li>KAMI TIDAK MENJAMIN AKURASI, KEASLIAN, KEUTUHAN ATAU KUALITAS KONTEN, SITUS ATAU SUMBER DAYA YANG TERSEDIA UNTUK DAN DARI SITUS TERMASUK, NAMUN TIDAK TERBATAS PADA, SETIAP GARANSI BAHWA KONTEN, SITUS ATAU SUMBER BEBAS DARI SUMBER MATERI YANG BERSIFAT MERUSAK, TIDAK SENONOH ATAU KONTROVERSIAL;</li>
                <li>KAMI TIDAK MENJAMIN ATAU MENANGGUNG BAHWA ANDA AKAN DIBERIKAN IZIN PERJALANAN YANG SAH YANG BERLAKU UNTUK ANDA. KAMI TIDAK BERTANGGUNG JAWAB APAPUN UNTUK MEMBERITAHU ANDA ATAU MEMBERI GANTI KERUGIAN KEPADA ANDA DALAM HAL ANDA MENGALAMI KERUGIAN ATAU KERUSAKAN SEHUBUNGAN DENGAN TIDAK ADANYA VISA ATAU IZIN PERJALANAN ANDA (TERMASUK, NAMUN TIDAK TERBATAS PADA, PENOLAKAN UNTUK MASUK KE DALAM SUATU NEGARA, DEPORTASI);</li>
                <li>SETIAP MATERI UNDUHAN ATAU LAINNYA YANG DIPEROLEH MELALUI PENGGUNAAN LAYANAN INI MERUPAKAN TANGGUNG JAWAB DAN RISIKO ANDA SENDIRI. ANDA SECARA SUKARELA MENANGGUNG RISIKO TERSEBUT, DAN ANDA AKAN SEPENUHNYA BERTANGGUNG JAWAB ATAS KERUGIAN ATAU KERUSAKAN YANG TIMBUL DARI ATAU SEHUBUNGAN DENGAN MATERI TERSEBUT, TERMASUK SETIAP KERUSAKAN PADA SISTEM KOMPUTER ANDA ATAU HILANGNYA DATA YANG TERJADI AKIBAT MENGUNDUH MATERI APAPUN YANG DISEDIAKAN; DAN</li>
                <li>TANPA BERPRASANGKA TERHADAP APA YANG DIATUR DALAM KETENTUAN, KEWAJIBAN MASING-MASING PIHAK TERBATAS DAN DIKECUALIKAN SEMAKSIMALNYA YANG DIIZINKAN OLEH HUKUM, SEPERTI UNTUK CEDERA PRIBADI DAN KEMATIAN. KAMI TIDAK AKAN BERTANGGUNG JAWAB ATAS SETIAP KERUGIAN ATAU KERUSAKAN, BAIK LANGSUNG ATAU TIDAK LANGSUNG, AKIBAT DARI ATAU TERHUBUNG KE PENGGUNAAN ANDA TERHADAP SITUS INI ATAU PENGGUNAAN TAUTAN PADA SITUS, TERMASUK NAMUN TIDAK TERBATAS PADA KERUSAKAN KHUSUS, INSIDENTAL, HUKUMAN ATAU KERUSAKAN AKIBAT ATAU KERUGIAN EKONOMI LAINNYA, MESKIPUN KAMI TELAH DIBERITAHU TENTANG KEMUNGKINAN KERUGIAN ATAU KERUSAKAN YANG MUNGKIN TERJADI. PERBAIKAN SATU-SATUNYA YANG TERSEDIA BAGI ANDA ADALAH PENGHENTIAN PENGGUNAAN SITUS INI.</li>
              </ol>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>P. Ganti Rugi</h6>
              <p className='mt-4'>Anda dengan ini setuju untuk mengganti kerugian dan tidak menyalahkan SightSea dan karyawannya, afiliasi, staff dan mitra, dari dan terhadap setiap dan semua klaim, tuntutan, kewajiban, kerusakan atau kerugian termasuk biaya hukum, yang timbul sebagai akibat dari klaim pihak ketiga sehubungan dengan: </p>
              <ol className='list-decimal pl-8 mt-4'>
                <li>penggunaan Anda terhadap Situs;</li>
                <li>konten yang diberikan, disediakan atau diakses melalui Situs ini;</li>
                <li>pelanggaran Anda terhadap Syarat tersebut;</li>
                <li>pelanggaran hak atau kewajiban lainnya; dan/atau</li>
                <li>setiap tindakan atau kelalaian oleh Anda, baik lalai, melanggar hukum atau lainnya.</li>
              </ol>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>Q. Tautan Dan Konten Pihak Ketiga</h6>
              <p className='mt-4'>Kami dapat menyediakan tautan ke situs-situs lainnya yang dikelola oleh pihak lain (termasuk namun tidak terbatas pada situs-situs yang pada mana Anda dapat melakukan dan/atau menyelesaikan transaksi tertentu), dengan mengeklik tautan, Anda dengan ini menyatakan, mengakui dan setuju bahwa tindakan tersebut merupakan tindakan sukarela Anda untuk melihat atau mengunjungi situs lain tersebut.</p>
              <p className='mt-4'>Kami tidak mengontrol situs-situs atau tautan ke situs web yang dioperasikan oleh pihak lain selain SightSea dan tidak bertanggung jawab atas konten atau privasi atau kegiatan lain dari situs tersebut. Kami, atau pihak ketiga lainnya, dapat mengunggah secara otomatis hasil pencarian atau memberikan tautan ke situs lain. Kami memberikan kesempatan bagi pihak ketiga untuk memberikan, memuat, mengirimkan atau sebaliknya menyediakan Konten melalui Situs ini.</p>
              <p className='mt-4'>Kami tidak meninjau dan/atau tidak memiliki kontrol atas situs, sumber, dan Konten. Anda setuju bahwa Kami tidak bertanggung jawab atas Konten atau ketersediaan situs dan sumber daya tersebut, dan Kami tidak mendukung atau merekomendasikan dan tidak bertanggung jawab atas asal-usul situs atau Konten. Anda setuju untuk membebaskan Kami dari dan terhadap setiap dan semua kewajiban, pengeluaran, kerugian, atau kerusakan, secara langsung atau tidak langsung yang disebabkan atau diduga disebabkan oleh atau sehubungan dengan penggunaan atau akun untuk Konten, situs atau sumber daya.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>R. Pengakhiran</h6>
              <p className='mt-4'>SightSea memiliki kebijakan mutlak dan penuh untuk mengubah, menunda, tidak melanjutkan atau menghentikan Situs ini dan/atau bagian Situs, termasuk layanan atau produk yang disediakan dalam Situs ini, dan/atau penggunaan Situs ini, atau bagiannya, kapan saja dengan alasan apa pun tanpa pemberitahuan sebelumnya kepada Anda.</p>
              <p className='mt-4'>Dalam hal terjadi pengakhiran, Anda tetap terikat oleh kewajiban dalam Ketentuan ini, termasuk namun tidak terbatas pada jaminan, ganti rugi, pelepasan dan pembatasan kewajiban yang telah Anda sepakati, sehubungan dengan Layanan apa pun yang telah diberikan kepada Anda tetapi belum sepenuhnya diberikan pada tanggal pengakhiran. SightSea tidak akan bertanggung jawab kepada Anda atau pihak ketiga mana pun atas penghentian atau penangguhan akses Anda ke Situs.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>S. Perlindungan Data Pribadi</h6>
              <p className='mt-4'>Pemberitahuan Privasi merupakan bagian integral dari Syarat ini. Silakan lihat Persyaratan Privasi Penggunaan Data Pribadi untuk meninjau Pemberitahuan Privasi kami, yang juga mengatur penggunaan anda terhadap Situs, untuk memahami praktik kami.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>T. Hukum Yang Mengatur</h6>
              <p className='mt-4'>Ketentuan ini (dan setiap dan semua perselisihan yang timbul dari atau sehubungan dengan Ketentuan ini (termasuk dugaan pelanggaran atau tantangan terhadap keabsahan atau keberlakuan Ketentuan ini)) akan diatur oleh dan ditafsirkan hanya sesuai dengan Hukum Republik Indonesia.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>U. Penyelesaian Perselisihan</h6>
              <p className='mt-4'>Segala perselisihan yang timbul dari atau sehubungan dengan Ketentuan ini dan Layanan, termasuk segala pertanyaan terkait keabsahan, atau pemutusan, Para Pihak akan menyelesaikan dengan cara musyawarah dengan itikad baik untuk mencapai mufakat dalam waktu enam puluh (60) hari sejak tanggal pemberitahuan tentang adanya perselisihan. Namun, jika perselisihan tersebut tidak dapat diselesaikan melalui musyawarah dalam waktu enam puluh (60) hari, maka perselisihan tersebut wajib dirujuk ke dan diputuskan melalui Badan Arbitrase Nasional Indonesia (BANI). Kedudukan arbitrase tersebut harus dilakukan di Indonesia.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>V. Lain-Lain</h6>
              <p className='mt-4'>Ketentuan yang tercantum dalam Syarat ini dan setiap perjanjian dan kebijakan yang disertakan atau dirujuk dalam Syarat ini membentuk seluruh perjanjian dan pemahaman antara para pihak sehubungan dengan Layanan dan Situs dan menggantikan setiap perjanjian atau pemahaman sebelumnya antara para pihak sehubungan dengan hal tersebut. Dengan ini para pihak juga mengecualikan semua ketentuan yang tersirat. Dalam memasuki perjanjian yang dibentuk oleh Syarat ini, para pihak tidak bersandar pada informasi, pernyataan, garansi, pemahaman, kesanggupan, janji atau jaminan siapa pun selain yang secara tegas diatur dalam Syarat ini.</p>
              <p className='mt-4'>Jika Anda menggunakan Situs untuk atau atas nama pihak ketiga, seperti anggota keluarga atau teman perjalanan, maka pihak ketiga tersebut dianggap telah menyetujui dan mengikatkan dirinya terhadap seluruh ketentuan yang terdapat dalam Syarat ini. Anda bertanggung jawab atas setiap kesalahan dalam keakuratan informasi yang diberikan sehubungan dengan penggunaan tersebut. Selain itu, Anda harus menginformasikan pihak ketiga tersebut dari semua syarat dan ketentuan yang berlaku. Bila menggunakan Situs untuk atau atas nama pihak ketiga, Anda setuju untuk mengganti kerugian dan tidak menyalahkan SightSea dari dan terhadap setiap dan semua kewajiban, kerugian, kerusakan, gugatan dan klaim termasuk biaya hukum, yang timbul dari atau terhubung dengan pelanggaran Syarat tersebut atau kelalaian oleh Anda dan/atau pihak ketiga tersebut.</p>
              <p className='mt-4'>Segala bentuk kerugian atau kehilangan atau klaim yang diajukan oleh pihak ketiga terkait dengan Layanan dan/atau Situs akan diselesaikan berdasarkan ketentuan yang terdapat pada Syarat ini. Ketentuan ini dibuat dalam Bahasa Indonesia.</p>
              <p className='mt-4'>Dalam hal bahwa ketentuan apa pun dalam Ketentuan ini ditetapkan untuk tidak dapat dilaksanakan atau tidak sah, oleh pengadilan dari yurisdiksi yang kompeten, maka ketentuan tersebut akan tetap diberlakukan sejauh diizinkan oleh hukum yang berlaku dan ketetapan tersebut tidak akan mempengaruhi validitas dan keberlakuan dari setiap ketentuan lainnya yang tersisa. Ketentuan yang terputus harus digantikan dengan ketentuan yang mendekati kata-kata asli dan maksud sebanyak mungkin. Kegagalan salah satu pihak untuk melaksanakan setiap ketentuan dari Ketentuan ini setiap saat tidak akan ditafsirkan sebagai pelepasan hak masing-masing pihak di waktu kemudian untuk memberlakukan ketentuan atau ketentuan lainnya dalam Ketentuan ini kecuali ketentuan tersebut dikesampingkan secara tertulis.</p>
              <p className='mt-4'>Anda tidak dapat menyerahkan atau mengalihkan hak atau kewajiban Anda menurut Ketentuan ini, tanpa persetujuan tertulis Kami sebelumnya. SightSea dapat mengalihkan, mensublisensikan atau memindahkan hak apapun yang diberikan kepada SightSea atau mensubkontrakkan salah satu kewajiban SightSea dalam memberikan Layanan pada Situs. Kecuali dinyatakan lain, tidak ada dalam Ketentuan ini yang dimaksudkan untuk memberikan kepada pihak ketiga mana pun setiap hak untuk melaksanakan syarat apa pun atau untuk memberikan pada pihak ketiga manfaat apa pun menurut Ketentuan ini. Pemberitahuan yang diberikan sesuai dengan Ketentuan ini akan dianggap cukup diberikan jika dibuat secara tertulis dan diteruskan melalui pos tercatat atau layanan pengiriman tercatat atau yang setara dengan salah satu Pihak (di alamat terdaftar Kami, atau diberitahukan). SightSea dapat memberikan pemberitahuan kepada Anda melalui pemberitahuan umum yang dipublikasikan di Situs atau ke alamat surat elektronik Anda yang tercantum di akun Anda. Anda harus memberikan pemberitahuan kepada SightSea melalui pos tercatat atau layanan pengiriman tercatat atau yang setara dengan salah satu Pihak (di alamat terdaftar Kami, atau diberitahukan).</p>
              <p className='mt-4'>Dengan menggunakan Layanan Kami, Anda mengetahui bahwa Kami mungkin perlu tunduk kepada syarat dan ketentuan tambahan yang dibuat oleh PIHAK KETIGA yang bekerja sama dengan kami Anda setuju untuk mematuhi semua hukum, undang-undang, peraturan dan kode yang berlaku, termasuk setiap perubahannya (apabila ada), terhadap transaksi yang Anda lakukan dengan SightSea, termasuk ketentuan yang berkaitan dengan anti penyuapan dan anti korupsi.</p>
            </div>
            <div className='my-5'>
              <h6 className='font-bold underline uppercase'>W. Force Majeure</h6>
              <p className='mt-4'>SightSea tidak akan bertanggung jawab atas performa yang tidak dilakukan atau pelanggaran Syarat ini, seperti kegagalan transaksi, akses terbatas ke Situs, atau setiap kerusakan atau bahaya kepada pengguna yang disebabkan oleh tindakan atau kondisi apa pun di luar kontrol yang wajar baik oleh Anda atau Kami (“Peristiwa Force Majeure“). Peristiwa Force Majeure termasuk namun tidak terbatas pada bencana alam (banjir, gempa bumi), epidemi, kerusuhan, pernyataan perang, perang, aksi militer, tindakan teroris, embargo, sanksi, perubahan undang-undang atau peraturan, petir, badai/topan/siklon, mogok kerja, demonstrasi, kepailitan atau insolvensi maskapai penerbangan atau hotel, dan serangan siber.</p>
              <p className='mt-4'>SightSea tidak akan bertanggung jawab atas setiap kerusakan atau kerugian yang disebabkan oleh cara apa pun kepada pihak mana pun jika SightSea tidak dapat memproses pesanan Anda karena Peristiwa Force Majeure.</p>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
};
